# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:year/:month/:title/

# Setup
title:            Jiamin Zhu
tagline:          My Notebook
description:      Research, Outdoor Activities, Language, Tech, Travel, Online Learning, Settle Down, Random Thoughts, Novels ...
url:              https://jiamin.io
baseurl:          /
author:
  name:           Jiamin Zhu
  url:            https://jiamin.io
paginate:         4
repository:       walkerwalker/jiamin.io
github:
  repo:           https://github.com/walkerwalker/jiamin.io
  markdown:	  CommonMarkGhPages
# Plugins, Tags, Categories and Analytics  
# plugins:          [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

# tags:

# google_analytics:
#  tracking_id:    UA-2228390-1
